### ISSUE TITLE
Bauer - The Divider.issue() function may not work.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-sense-judging#15]
Bauer

high

# The Divider.issue() function may not work.

## Summary
There is no check for issuance fees at  Adapter contract initialization and there is no update fee function. If the `ifee` is larger than the `ISSUANCE_FEE_CAP`, the `Divider.issue()` function will not work.

## Vulnerability Detail
The `Divider.issue()` is used to mint Principal & Yield Tokens of a specific Series. Inside the `issue()` function, the protocol will take the issuance fee out of the deposited Target, and put it towards the settlement reward. The issuance fee is calculated according to the formula `uint256 issuanceFee = Adapter(adapter).ifee()` and it needs to meet the conditions `if (issuanceFee > ISSUANCE_FEE_CAP) revert Errors.IssuanceFeeCapExceeded()`. However,the adapter contract is not checked for issuance fees at initialization and there is no update fee function. If the `ifee` is larger than the `ISSUANCE_FEE_CAP`, the `Divider.issue()` function will not work.
```solidity
function issue(
        address adapter,
        uint256 maturity,
        uint256 tBal
    ) external nonReentrant whenNotPaused returns (uint256 uBal) {
        if (!adapterMeta[adapter].enabled) revert Errors.InvalidAdapter();
        if (!_exists(adapter, maturity)) revert Errors.SeriesDoesNotExist();
        if (_settled(adapter, maturity)) revert Errors.IssueOnSettle();

        uint256 level = adapterMeta[adapter].level;
        if (level.issueRestricted() && msg.sender != adapter) revert Errors.IssuanceRestricted();

        ERC20 target = ERC20(Adapter(adapter).target());

        // Take the issuance fee out of the deposited Target, and put it towards the settlement reward
        uint256 issuanceFee = Adapter(adapter).ifee();
        if (issuanceFee > ISSUANCE_FEE_CAP) revert Errors.IssuanceFeeCapExceeded();
        uint256 fee = tBal.fmul(issuanceFee);
```
```solidity
    constructor(
        address _divider,
        address _target,
        address _underlying,
        uint128 _ifee,
        AdapterParams memory _adapterParams
    ) {
        divider = _divider;
        target = _target;
        underlying = _underlying;
        ifee = _ifee;
        adapterParams = _adapterParams;

        name = string(abi.encodePacked(ERC20(_target).name(), " Adapter"));
        symbol = string(abi.encodePacked(ERC20(_target).symbol(), "-adapter"));

        ERC20(_target).safeApprove(divider, type(uint256).max);
        ERC20(_adapterParams.stake).safeApprove(divider, type(uint256).max);
    }
```

## Impact
The `Divider.issue()` function may not work.
## Code Snippet
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Divider.sol#L208
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/adapters/abstract/BaseAdapter.sol#L80

## Tool used

Manual Review

## Recommendation
ensure `_ifee` < = `ISSUANCE_FEE_CAP` in the ` Adapter contract.

**Comment by jparklev** [comment]
Disputed: 
> If the ifee is larger than the ISSUANCE_FEE_CAP, the Divider.issue() function will not work.

That's exactly what should happen if you try to deploy an adapter with a large issuance fee, it should not work. You would need to redeploy the adapter with a lower issuance fee.
