### ISSUE TITLE
Saeedalipoor01988 - Give an infinite allowance to the `spender` that provided by user to spend contract's `sellToken`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-sense-judging#2]
Saeedalipoor01988

high

# Give an infinite allowance to the `spender` that provided by user to spend contract's `sellToken`

## Summary
Periphery.sol#L902._fillQuote function is giving infinite allowance to address that is provided by the user.

## Vulnerability Detail
in the Periphery.sol#L902._fillQuote function, the Periphery contract is giving infinite allowance to address that is provided by the user, to spend the contract's `sellToken`.

Any user can make a call to the Periphery.sol#L116.sponsorSeries function to  Sponsor a new Series in any adapter previously onboarded onto the Divider. One of the inputs in this function is the SwapQuote calldata quote. SwapQuote struct including :

>     struct SwapQuote {
>         ERC20 sellToken;
>         ERC20 buyToken;
>         address spender;
>         address payable swapTarget;
>         bytes swapCallData;
>     }

So user can use any address as a spender address. then in the Periphery.sol#L902._fillQuote function, we make a call to the Periphery.sol#L902._fillQuote function. in this function, at line Periphery.sol#L907, the Periphery contract gives `spender` an infinite allowance to spend this contract's `sellToken`.

So anytime, when the Periphery contract has a balance of more than zero for `sellToken`, the `spender` address can use transferFrom to withdraw the balance of `sellToken`.

## Impact
When you give an infinite allowance to the `spender` address for `sellToken`, `spender` can use front-run, and anytime the Periphery contract has a balance of more than zero for `sellToken`,  `spender` can withdraw it.

## Code Snippet
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L90
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L121
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L125
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L907

## Tool used
Manual Review

## Recommendation
Don't give infinite allowance to the `spender`, just use the amount that is needed.

**Comment by jparklev** [comment]
Disputed: In the case that spender is not the 0x contract, Periphery would indeed be approving another address. But, since the Periphery never holds any token or ETH, this does not have any impact
