### ISSUE TITLE
foxb868 - An attack can reenter and steal funds from the BaseAdapter contract through the FlashLoan Function.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-sense-judging#21]
foxb868

medium

# An attack can reenter and steal funds from the BaseAdapter contract through the FlashLoan Function.

## Summary
The "flashLoan" function of the "BaseAdapter" contract is vulnerable to reentrancy attacks due to calling the `onFlashLoan` function of the receiver contract before transferring the borrowed amount of target tokens from the receiver contract to the "BaseAdapter" contract.
This allows a malicious receiver contract to call back the `flashLoan` function before the transfer is complete, causing unintended consequences such as stealing funds from the "BaseAdapter" contract.

## Vulnerability Detail
The "BaseAdapter" contract is that the `onFlashLoan` function of the receiver contract is called before transferring the borrowed amount of target tokens from the receiver contract to the "BaseAdapter" contract. This creates a potential reentrancy vulnerability as the receiver contract could call back the `flashLoan` function again before the transfer is complete, leading to unintended consequences.

Specifically, the issue is with the `flashLoan` function, which can be found starting on line 95 of the code.
Here is the relevant code:
```solidity
    function flashLoan(
        IERC3156FlashBorrower receiver,
        address, /* fee */
        uint256 amount,
        bytes calldata data
    ) external returns (bool) {
        if (Divider(divider).periphery() != msg.sender) revert Errors.OnlyPeriphery();
        ERC20(target).safeTransfer(address(receiver), amount);
        bytes32 keccak = IERC3156FlashBorrower(receiver).onFlashLoan(msg.sender, target, amount, 0, data);
        if (keccak != CALLBACK_SUCCESS) revert Errors.FlashCallbackFailed();
        ERC20(target).safeTransferFrom(address(receiver), address(this), amount);
        return true;
    }
```
As you can see, the `onFlashLoan` function of the receiver contract is called before the borrowed amount of target tokens is transferred from the receiver contract back to the "BaseAdapter" contract, this creates a potential "reentrancy" vulnerability, as the receiver contract could call back the `flashLoan` function again before the transfer is complete.

## Impact
This can result in the loss of a large amount of funds, and could also affect other contracts that depend on the `BaseAdapter` contract for liquidity.

## Code Snippet
https://github.com/sense-finance/sense-v1/blob/82abac25404d83b7aefaaeb46631f1d050dc4a4e/pkg/core/src/adapters/abstract/BaseAdapter.sol#L103
https://github.com/sense-finance/sense-v1/blob/82abac25404d83b7aefaaeb46631f1d050dc4a4e/pkg/core/src/adapters/abstract/BaseAdapter.sol#L95-L107
## Tool used

Manual Review

## Recommendation
The `flashLoan` function should transfer the borrowed amount of target tokens back to the `BaseAdapter` contract before calling the `onFlashLoan` function of the receiver contract. Here is the fixed code:
```solidity
function flashLoan(
    IERC3156FlashBorrower receiver,
    address, /* fee */
    uint256 amount,
    bytes calldata data
) external returns (bool) {
    ERC20(target).safeTransfer(address(receiver), amount);
    ERC20(target).safeTransferFrom(address(receiver), address(this), amount);
    bytes32 keccak = IERC3156FlashBorrower(receiver).onFlashLoan(msg.sender, target, amount, 0, data);
    return true;
}
```

**Comment by jparklev** [comment]
Disputed: The receiver contract is always the Periphery, so it can be trusted to not be malicious for valid adapters
