### ISSUE TITLE
0x52 - Periphery#addLiquidity won't work correcty for issue restricted adapters

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-sense-judging#34]
0x52

medium

# Periphery#addLiquidity won't work correcty for issue restricted adapters

## Summary

Some adapters are issuance restricted meaning that they can't be issued unless the adapter directly mints from divider. The current structure of Periphery#addLiquidity always requires calling divider#issue. This means that Periphery won't be able to add liquidity for these adapters.

## Vulnerability Detail

See summary.

## Impact

Periphery#addLiquidity won't work correcty for issue restricted adapters

## Code Snippet

https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L656-L680

## Tool used

Manual Review

## Recommendation

For issue restricted adapters the contract should swap everything for target and then add single sided liquidity using only the target.

**Comment by jparklev** [comment]
Disputed: The periphery has been designed to work with adapters where issuance is not restricted. Therefore, such adapters would require another type of Periphery.
