### ISSUE TITLE
spyrosonic10 - _swapYTsForTarget() is expected to be private but exposed for public

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-sense-judging#37]
spyrosonic10

high

# _swapYTsForTarget() is expected to be private but exposed for public

## Summary
`swapYTsForTarget()` allowed to be called by adapter only . But another method named `_swapYTsForTarget()` is expected be internal method but it is exposed to public. 

## Vulnerability Detail
Public can call  method `_swapYTsForTarget()` directly which is expected to be `adapterOnly` method

## Impact
Public can call  method `_swapYTsForTarget()` directly which is expected to be `adapterOnly` method

## Code Snippet
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L565-L581

## Tool used

Manual Review

## Recommendation
change `_swapYTsForTarget()` to internal

**Comment by hrishibhat** [comment]
Considering this issue as informational
