### ISSUE TITLE
chainNue - Adversary can drain ether or ERC20 token from `RollerPeriphery` contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-sense-judging#42]
chainNue

high

# Adversary can drain ether or ERC20 token from `RollerPeriphery` contract

## Summary

Adversary can withdraw ether or ERC20 tokens from `RollerPeriphery` contract with a custom `AutoRoller` 

## Vulnerability Detail

The `redeem` function in `RollerPeriphery`, provide several parameters, in which can be easily manipulated. An adversary can create an `AutoRoller` contract which is designed to bypass the `redeem` function statement and at the end will return the Ether from contract. Details as follows:

L105: `_transferFrom(permit, address(roller), shares);` can be bypassed since the roller contract is from the input parameter, adversary just need to make sure the fake `roller` can transfer their ERC20 token with `shares` amount.

L107: `_fromTarget` will decide the `amtOut`, while `minAmountOut` can be just set 0.  
```solidity
File: RollerPeriphery.sol
284:     function _fromTarget(
285:         address adapter,
286:         uint256 _amt,
287:         SwapQuote calldata quote
288:     ) internal returns (uint256 amt) {
289:         if (address(quote.buyToken) == AdapterLike(adapter).underlying()) {
290:             amt = AdapterLike(adapter).unwrapTarget(_amt);
291:         } else if (address(quote.buyToken) != AdapterLike(adapter).target()) {
292:             AdapterLike(adapter).unwrapTarget(_amt);
293:             // sell underlying for quote.buyToken
294:             amt = _fillQuote(quote);
295:         } else {
296:             amt = _amt;
297:         }
298:     }
```
the `_fromTarget` parameters which came from `_fromTarget(address(roller.adapter()), roller.redeem(shares, address(this), address(this)), quote)` are user's input.
- adapter came from `roller.adapter()` can be manipulated
- _amt came from `roller.redeem()` can be manipulated
- quote can be manipulated

thus, this `_fromTarget` amt return value can be controlled by adversary.

finally, L110 - L112 can easily be executed to drain ether or ERC20 tokens from contract.

On a side note, we also assume the `RollerPeriphery` will contains some amount of ether because of 
```solidity
File: RollerPeriphery.sol
338:     // required for refunds
339:     receive() external payable {}
```

This `AutoRoller` input as parameters also exists in some other function like `withdrawUnderlying` which will cause similar effect.

## Impact

Adversary can drain ether or any ERC20 tokens from `RollerPeriphery`

## Code Snippet

https://github.com/sherlock-audit/2023-03-sense/blob/main/auto-roller/src/RollerPeriphery.sol#L104-L115

```solidity
File: RollerPeriphery.sol
104:     function redeem(AutoRoller roller, uint256 shares, address receiver, uint256 minAmountOut, PermitData calldata permit, SwapQuote calldata quote) external returns (uint256 amtOut) {
105:         _transferFrom(permit, address(roller), shares);
106: 
107:         if ((amtOut = _fromTarget(address(roller.adapter()), roller.redeem(shares, address(this), address(this)), quote)) < minAmountOut) {
108:             revert MinAmountOutError();
109:         }
110:         address(quote.buyToken) == ETH
111:             ? payable(receiver).transfer(amtOut)
112:             : ERC20(address(quote.buyToken)).safeTransfer(receiver, amtOut); // transfer bought tokens to receiver
113: 
114:         _transferRemainingUnderlying(roller, receiver);
115:     }
```
## Tool used

Manual Review

## Recommendation

Register `roller` contracts in `RollerPeriphery` and use it for source of truth, rather than blindly accepting user's input parameter for the roller contract. (in `Divider.sol`, it's like `AdapterMeta` mapping)

**Comment by chainNue** [comment]
Escalate for 10 USDC

There are some valid issue submissions (#29 , #38 )  related to excess tokens held in contract when doing swapping, (for example, in the `RollerPeriphery` are 
- deposit -> _toTarget -> _fillQuote 
- redeem -> _fromTarget -> _fillQuote 

Those issues are medium because the excess fund should be returned, while in this issue, it's about adversary can withdraw those un-returned funds, so it's should be a valid High (and NOT a duplicate with the `excess fund should be returned` issue)

**Comment by hrishibhat** [comment]
Escalation rejected

Because the contract clearly does not expect any tokens to be held, being able to drain ether/tokens is not a valid issue in this case. 
Whereas the other issues pointed out in the escalation show how funds can remain in the contract, while clearly they are not supposed to.
