### ISSUE TITLE
Saeedalipoor01988 - a minAccepted in the _balancerSwap coded to 0 and allows frontrunning

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-sense-judging#5]
Saeedalipoor01988

high

# a minAccepted in the _balancerSwap coded to 0 and allows frontrunning

## Summary
The Periphery.sol#L531._swapPTsForTarget function is calling the _balancerSwap function to make a swap on Balancer protocol with 0 limit ("minAccepted") in return!

## Vulnerability Detail
in the Periphery.sol#L531._swapPTsForTarget function, we make the call to the _balancerSwap function with minAccepted = 0.

>     function _swapPTsForTarget(
>         address adapter,
>         uint256 maturity,
>         uint256 ptBal,
>         PermitData calldata permit
>     ) internal returns (uint256 tBal) {
>         _transferFrom(permit, divider.pt(adapter, maturity), ptBal);
> 
>         if (divider.mscale(adapter, maturity) > 0) {
>             tBal = divider.redeem(adapter, maturity, ptBal);
>         } else {
>             tBal = _balancerSwap(
>                 divider.pt(adapter, maturity),
>                 Adapter(adapter).target(),
>                 ptBal,
>                 BalancerPool(spaceFactory.pools(adapter, maturity)).getPoolId(),
>                 0,
>                 payable(address(this))
>             );
>         }
>     }

The function _balancerSwap at Periphery.sol#L902, creates the needed parameter for making a swap on the Balancer.swap function and makes calls to the balancerVault.swap with minAccepted or limit = 0.

> 
>   function _balancerSwap(
>         address assetIn,
>         address assetOut,
>         uint256 amountIn,
>         bytes32 poolId,
>         uint256 minAccepted,
>         address payable receiver
>     ) internal returns (uint256 amountOut) {
>         ERC20(assetIn).safeApprove(address(balancerVault), amountIn);
> 
>         BalancerVault.SingleSwap memory request = BalancerVault.SingleSwap({
>             poolId: poolId,
>             kind: BalancerVault.SwapKind.GIVEN_IN,
>             assetIn: IAsset(assetIn),
>             assetOut: IAsset(assetOut),
>             amount: amountIn,
>             userData: hex""
>         });
> 
>         BalancerVault.FundManagement memory funds = BalancerVault.FundManagement({
>             sender: address(this),
>             fromInternalBalance: false,
>             recipient: receiver,
>             toInternalBalance: false
>         });
> 
>         amountOut = balancerVault.swap(request, funds, minAccepted, type(uint256).max);
>         emit Swapped(msg.sender, poolId, assetIn, assetOut, amountIn, amountOut, msg.sig);
>     }

the minAccepted, in the Balancer.swap function, is called limit. The meaning of limit depends on the value of singleSwap.kind

>     GIVEN_IN: The minimum amount of tokens to receive from the swap.
>     GIVEN_OUT: The maximum amount of tokens to send for the swap.

and in the request that is created in the _balancerSwap function, kind: BalancerVault.SwapKind.GIVEN_IN. **that means The minimum amount of tokens to receive from the swap.** so the minimum amount of tokens to receive from the swap is hardcoded to 0.

Based on the below code from balancer Swap contract, it's possible Periphery contract run a swap with a loss.

>         _require(singleSwap.kind == SwapKind.GIVEN_IN ? amountOut >= limit : amountIn <= limit, Errors.SWAP_LIMIT);

This allows malicious bots or malicious users to front-run on the mempool and by manipulating the pool, it can cause a loss of funds.

1 - Periphery contract sends the transaction to swap 100 tokens and get 90 tokens in return.
2 - malicious bots or malicious users front-run on the mempool and see this transaction.
3 - malicious bots or malicious users create a new transaction with a higher gas fee to manipulate the pool. " MEV BOT".
4 - now the swap rate gets changed.
5 - the swap transaction Periphery contract gets processed with the loss on return. return amount >= 0 ! instead of 90 tokens.
6 - malicious bots or malicious users create a new transaction to make another swap and generate profit from it.

## Impact
The swap transaction can cause a loss of funds and receive less money than the actual amount.

## Code Snippet
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L547
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L505
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L513
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L527
https://github.com/balancer/balancer-v2-monorepo/blob/72e5d0cd0bfeb7b7466596be53ad8db54fb67703/pkg/vault/contracts/Swaps.sol#L61
https://github.com/balancer/balancer-v2-monorepo/blob/72e5d0cd0bfeb7b7466596be53ad8db54fb67703/pkg/vault/contracts/Swaps.sol#L100

## Tool used
Manual Review

## Recommendation
Use an minAccepted that won't cause loss.

**Comment by jparklev** [comment]
Disputed: the only function that calls this internal function uses the `minAccepted` slippage check
