### ISSUE TITLE
Saeedalipoor01988 - All ETH balance of Periphery contract get sent to the user from _fillQuote function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-sense-judging#6]
Saeedalipoor01988

high

# All ETH balance of Periphery contract get sent to the user from _fillQuote function

## Summary
In the Periphery.sol#L902._fillQuote function, the contract is sending all ETH balance to the function caller.

## Vulnerability Detail
In the _fillQuote function at Periphery.sol#L928, there is code that is refunding any unspent protocol fees (paid in ether) to the sender.

>         // Refund any unspent protocol fees (paid in ether) to the sender.
>         uint256 refundAmt = address(this).balance;
>         if (address(quote.buyToken) == ETH) refundAmt = refundAmt - boughtAmount;
>         payable(msg.sender).transfer(refundAmt);

And there is receive function at Periphery.sol#L1025 to accept ETH to Periphery contract.

>   receive() external payable {}

Imagin that contract has 20 ETH balance and quote.buyToken is ETH and boughtAmount is 3 ETH. now :

> uint256 refundAmt = address(this).balance = 20 ETH
> if (address(quote.buyToken) == ETH) refundAmt = 20 ETH - 3 ETH  = 17 ETH

The Periphery contract will send 17 ETH to the caller of function. or if quote.buyToken is not ETH, contract will send 20 ETH to the user.

## Impact
ETH balance of contract get loose because in the Periphery.sol#L902._fillQuote function, the contract is sending all ETH balance to the function caller for nothing !

## Code Snippet
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L1025
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L928

## Tool used
Manual Review

## Recommendation
Use before balance and after balance.

**Comment by jparklev** [comment]
Disputed: the Periphery contract does not hold any tokens or ETH balance. If there is any, it is fine if the next user making an action gets it.
