### ISSUE TITLE
Bauer - Prevent users from sponsoring a new Series

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-sense-judging#8]
Bauer

high

# Prevent users from sponsoring a new Series

## Summary
An attacker can apply front-run attack by preventing users from sponsoring a new Series . 

## Vulnerability Detail
The ```Periphery.sponsorSeries()``` function is used to sponsor a new Series in any adapter previously onboarded onto the Divider. Inside the function, if adapters is verified or ```withPool``` is true,the protocol will call  the ```spaceFactory.create()``` function to deploy a Space contract. However, the ```spaceFactory``` protocol allows anyone to call the ```create()``` function. Here is the problem,a bad actor  can apply front-run attack and call the `create()`  function to prevent users from sponsoring a new Series.
1.Assume Alice  wants to Sponsor a new Series. So,  she calls the `sponsorSeries()`  function  with the following parameters:
     *  `adapter`: adapterA
    *   `maturity`: manturityA
    *   `withPool`: true
    * `permit`: permit
    *  `quote`:quote

2.Bob (a bad actor) notices Alice's transaction in the Mempool. So, Bob applies front-run attack and calls the `spaceFactory.create()` function with the following parameters:
    *   `adapter`: adapterA
    *   `maturity`: manturityA
By doing so,the protocol deploy a new `Space` contract.
`pools[adapter][maturity] = pool`

3.Then, when Alice's transaction is going to be executed, it fails because of ` _require(pools[adapter][maturity] == address(0), Errors.POOL_ALREADY_EXISTS)` in the `Space` contract.
    
```solidity
function sponsorSeries(
        address adapter,
        uint256 maturity,
        bool withPool,
        PermitData calldata permit,
        SwapQuote calldata quote
    ) external payable returns (address pt, address yt) {
        (, address stake, uint256 stakeSize) = Adapter(adapter).getStakeAndTarget();
        if (address(quote.sellToken) != ETH) _transferFrom(permit, stake, stakeSize);
        if (address(quote.sellToken) != stake) _fillQuote(quote);

        // Approve divider to withdraw stake assets
        ERC20(stake).safeApprove(address(divider), stakeSize);

        (pt, yt) = divider.initSeries(adapter, maturity, msg.sender);

        // Space pool is always created for verified adapters whilst is optional for unverified ones.
        // Automatically queueing series is only for verified adapters
        if (verified[adapter]) {
            spaceFactory.create(adapter, maturity);
        } else {
            if (withPool) {
                spaceFactory.create(adapter, maturity);
            }
        }

        // Refund any excess stake assets
        ERC20(stake).safeTransfer(msg.sender, ERC20(stake).balanceOf(address(this)));

        emit SeriesSponsored(adapter, maturity, msg.sender);
    }
```

```solidity
 /// @notice Deploys a new `Space` contract
    function create(address adapter, uint256 maturity) external returns (address pool) {
        address pt = divider.pt(adapter, maturity);
        _require(pt != address(0), Errors.INVALID_SERIES);
        _require(pools[adapter][maturity] == address(0), Errors.POOL_ALREADY_EXISTS);

        pool = address(new Space(
            vault,
            adapter,
            maturity,
            pt,
            ts,
            g1,
            g2,
            oracleEnabled
        ));

        pools[adapter][maturity] = pool;
    }
```

## Impact
Prevent users from sponsoring a new Series

## Code Snippet
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L134-L140
https://etherscan.io/address/0x5f6e8e9c888760856e22057cbc81dd9e0494aa34#code#F1#L75
## Tool used

Manual Review

**Comment by hrishibhat** [comment]
Agree with Sponsor's comment. 
Considering this issue as low
